<?php

namespace App\Repositories\Contact;

use App\Entities\Person;
use App\Repositories\EloquentRepository;
use Illuminate\Foundation\Application;

class PersonRepository extends EloquentRepository
{
    protected $modelInstance;


    public function __construct(Application $app, Person $modelInstance)
    {
        parent::__construct($app);
        $this->modelInstance = $modelInstance;
    }


    public function all(array $select = array('*'))
    {
        return parent::all($select); // TODO: Change the autogenerated stub
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function find($id, array $select = array('*'))
    {
        return parent::find($id, $select); // TODO: Change the autogenerated stub
    }

    public function update($id, array $data)
    {
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}