<?php

namespace App\Repositories\Currency;

use App\Entities\Currency;
use App\Repositories\Base\EloquentRepository;

class EloquentCurrencyRepository extends EloquentRepository
{
    protected $modelInstance;

    public function __construct(Currency $modelInstance)
    {
        $this->modelInstance = $modelInstance;
    }

    public function all(array $select = array('*'))
    {
        return parent::all($select); // TODO: Change the autogenerated stub
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function find($id, array $select = array('*'))
    {
        return parent::find($id, $select); // TODO: Change the autogenerated stub
    }

    public function update($id, array $data)
    {
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

}